### ISSUE TITLE
pdf_to_djvu_cgi.py does not find IA scan files

### ISSUE THREAD

**Issue by Tpt** [phil-el/phetools#10]
When IA-Upload calls pdf_to_djvu_cgi.py for file https://archive.org/details/ComeRuinareLAutoritaImage this error is returned:

`400 Bad Request` {"text": "invalid ia identifier, I can't locate needed files", "error": 2}

**Comment by phil-el** [comment]
Fixed by using the original pdf if Additional Text PDF doesn't exists. Note that this item has another problem, the pdf resolution is way too low and the produced DJVU is not readable.
