### ISSUE TITLE
fast_hocr seems to be completely broken

### ISSUE THREAD

**Issue by Hinote-github** [phil-el/phetools#2]
I'm trying to use the hocr service in the Russian Wikisource (calling it with &lang='ru' from my custom js in the meantime) and it returns "unable to locate file /data/project/phetools/cache/hocr/<...>.hocr for page <...>.djvu lang ru" to the callback for a page of some djvu files.

Job state is 'success' in the hocr queue after being 'pending' for long time... I tried hocr for some pages of 3 Russian djvu files (indexes and pages in ru WS while the djvu files are in commons) -- for 1 is okay and 2 failed...

More specifically, it fails with "unable to locate ... .hocr ..." for pages in [[s:ru:Индекс:Крестовский - Петербургские золотопромышленники.djvu|this index]](jobid=9966 in the hocr queue), where it runs fast_hocr() (I checked locally -- it runs fast_hocr() with no problem, has_word_bbox() returns True) and does not fall to slow_hocr(), while it runs okay for pages in [[s:ru:Индекс:Собрание сочинений Марка Твэна (1898) т.8.djvu|this index]], where it changes text falling into slow_ocr()...

I created an offline version of the tool and debugged locally into the tool logic and fast_hocr() ''seems to be completely broken'': djvu_text_to_hocr.do_parse() produces files with names page_NNNN.html (and then page_NNNN.html.bz2 after compession) in the cache_path catalog, while get_hocr() tries to fetch files with names which look like page_NNNN.hocr and page_NNNN.hocr.bz2 from the cache_path. So, hocr seems to work when it falls into slow_hocr() method and changes text from the existing OCR layer to the text produced by tesseract in slow_hocr(). However, if fast_hocr() has already ran and placed its output files into the cache_path, it does not fall into slow_hocr() and hocr() returns nothing while get_hocr() simply fails.

We do require the working fast_hocr() functionality in order to allow ru WS users simply split the pages with existing OCR layer into paragraphes. Thanks in advance.

[[s:ru:User:Hinote|Hinote (A)]]

**Comment by phil-el** [comment]
Thanks for the detailed report, it's fixed with https://github.com/phil-el/phetools/commit/908630db18ee1e1d000c6b7ced46fa8af0443178 

I have no way to test it on ru.ws as I dunno how to install the js side on this wiki. Also I need to rename filename on the server side, it's running but it'll take around 4 hours.

**Comment by Hinote-github** [comment]
> "I have no way to test it on ru.ws"
> Please look at your User Talk page at ru.ws. I could assist you there if further testing will be needed. Thanks alot for prompt actions. I'll test with other filenames by myself as well.
